### PR TITLE
Adding media queries

### PR DESCRIPTION
**Pull request by Tauqeer-Ahmed-99**
Added media queries at 800px breakpoint, and solved the glitch cancelling add movie by clicking on backdrop not resetting input fields

### CODE REVIEW

**Review by Tanvir04khan — APPROVED** [review]

**Review by faran4engg — COMMENTED** [review]
Dependent feature should be branched off from the previous feature. Nobody wants to review header and footer in this PR 🙂

**Comment by Tauqeer-Ahmed-99** [comment]
But then we will not get our previous feature's code on IDE, unless or until it has been merged to the master branch.

**Comment by faran4engg** [comment]
> But then we will not get our previous feature's code on IDE, unless or until it has been merged to the master branch.

But you can create branch from the previous PR branch 🙂

**Comment by faran4engg** [comment]
> > But then we will not get our previous feature's code on IDE, unless or until it has been merged to the master branch.
> 
> But you can create branch from the previous PR branch 🙂

Try this,
Create a new branch from adding-media-queries 
And add a console.log in a new branch
Raise a PR
Thank me later 🙂

**Comment by Tauqeer-Ahmed-99** [comment]
This is exactly what I've done in this whole project.

**Comment by faran4engg** [comment]
> This is exactly what I've done in this whole project. I 've created every new branch from last added feature branch. @faran4engg

I dont think so....... we were seeing the previous code... that should not happen.... lets join discord ... could you show how did u create feature branch ?

**Review by faran4engg — APPROVED** [review]
Amazing

**Review by coder-mezab — APPROVED** [review]

**Pull request merged**
